global:
  environment: local
  namespace: default

tags:
  ingress-nginx: false
  gateway: false
  loki: false
  grafana: false
  prometheus: false


jobs:
  enabled: false
  connections: false
  users: false
  variables: false
  migrations: false


image: teaglebuilt/fullflow:dev
pullPolicy: Always

ingress:
  enabled: false

network:
  enabled: false

webserver:
  expose: true
  port: 8080
  containerPort: 8080

postgresql:
  image: bitnami/postgresql:latest
  pullPolicy: IfNotPresent
  persistence:
    enabled: false


loki:
  persistence:
    enabled: false


grafana:
  persistence:
    enabled: false
