global:
  environment: local
  namespace: default

tags:
  ingress-nginx: true
  gateway: false
  loki: false
  grafana: false


jobs:
  enabled: false
  connections: false
  users: false
  variables: false
  migrations: false


image: teaglebuilt/fullflow:dev
pullPolicy: Always


webserver:
  port: 8080
  containerPort: 8080


db:
  image: bitnami/postgresql:latest
  pullPolicy: Always
  persistence:
    enabled: false


loki:
  persistence:
    enabled: false


grafana:
  persistence:
    enabled: false
