global:
  environment: "local"
  namespace: default

image: teaglebuilt/fullflow:dev
db:
  image: bitnami/postgresql:latest


gateway:
  image: elyra/enterprise-gateway:dev
  imagePullPolicy: IfNotPresent
  port: 8888
  replicas: 1
  logLevel: DEBUG
  mirrorWorkingDirs: false
  k8sMasterPublicIP:
  kernel:
    # Kernel cluster role created by this chart.
    clusterRole: kernel-controller
    # Will start kernels in the same namespace as EG if True.
    shareGatewayNamespace: false
    # Timeout for kernel launching in seconds.
    launchTimeout: 60
    # Timeout for an idle kernel before its culled in seconds. Default is 1 hour.
    cullIdleTimeout: 3600
    # List of kernel names that are available for use.
    whitelist:
        - r_kubernetes
        - python_kubernetes
        - python_tf_kubernetes
        - python_tf_gpu_kubernetes
        - scala_kubernetes
        - spark_r_kubernetes
        - spark_python_kubernetes
        - spark_scala_kubernetes
    # Default kernel name should be something from the whitelist
    defaultKernelName: python_kubernetes
  kernelspecs:
    # Optional custom data image containing kernelspecs to use.
    image:
    # Kernelspecs image pull policy.
    imagePullPolicy: Always
  kip:
    enabled: true
  # Kernel Image Puller image name and tag to use.
    image: elyra/kernel-image-puller:dev
  # Kernel Image Puller image pull policy.
    imagePullPolicy: IfNotPresent
  # Determines whether the Kernel Image Puller will pull kernel images it has previously pulled
    pullPolicy: IfNotPresent
  # The interval (in seconds) at which the Kernel Image Puller fetches kernelspecs to pull kernel images.
    interval: 300


  nfs:
    enabled: false
    # IP address of NFS server. Required if enabled.
    internalServerIPAddress: