environment: "local"

tags:
  nginx: false

labels: {}

networkPolicies:
  enabled: false

nodeSelector: {}
affinity: {}
tolerations: []


airflow:
  image: teaglebuilt/fullflow:dev


nginx:
  controller:
    service:
      loadBalancerIP: ""

prometheus:
  image: prom/prometheus:latest
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  serviceAccount: default
  securityContext:
    enabled: false
    runAsUser: 1000
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  volumeMounts:
    config: /etc/prometheus
    rules: /etc/prometheus/rules
    data: /prometheus
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: prometheus-claim
  - name: config
    configMap:
      name: prometheus-config
  - name: rules
    configMap:
      name: prometheus-rules
  service:
    name: prometheus-server
    port: 9090
  annotations:
    kubernetes.io/ingress.class: nginx
    prometheus.io/scrape: 'true'

statsd:
  enabled: true
  ports:
    ingest: 9125
    scrape: 9102
  image:
    name: prom/statsd-exporter
    tag: master
    pullPolicy: Always
  extraNetworkPolicies: []
  service:
    extraAnnotations: {}
  resources: {}
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi