global:
  environment: local
  namespace: default
  airflow:
    image: teaglebuilt/fullflow:dev
    executor: LocalExecutor
    paths:
      home: /usr/local/airflow
      dags: /usr/local/airflow/dags
  pgbouncer:
    enabled: true
    image: pgbouncer/pgbouncer:latest
    logDisconnections: true
    logConnections: true
    maxClientConn: 100
    verbose: true
  metrics:
    postgres:
      image: chriscowley/pgbouncer_exporter:latest

data:
  # If secret names are provided, use those secrets
  metadataSecretName: airflow-metadata
  resultBackendSecretName: ~
  fernetKeySecretName: airflow-fernet-key
  # Otherwise pass connection values in
  metadataConnection:
    user: airflow
    pass: postgresql
    host: postgresql
    port: 5432
    db: airflow
    sslmode: disable
    poolsize: 100
  resultBackendConnection:
    user: airflow
    pass: postgresql
    host: postgresql
    port: 5432
    db: airflow
    sslmode: disable
    poolsize: 100

deployment:
  webserver:
    replicas: 1
    resources:
      limits:
        memory: "512Mi"

  scheduler:
    replicas: 1
    resources:
      limits:
        memory: "512Mi"
  postgres:
    replicas: 1
    ports:
      pgbouncer: 5432
      pgbouncerScrape: 9127
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

service:
  webserver:
    type: ClusterIP
    ports:
      web: 8080
  scheduler:
    type: ClusterIP
    ports:
      logs: 8379
  postgres:

storage:
  webserver:
    enabled: true
  scheduler:
    enabled: true

networkPolicies:
  enabled: false

ingress:
  enabled: false

nodeSelector: {}

affinity: {}

tolerations: []
