global:
  environment: "local"
  namespace: default

tags:
  traefik: false
  gateway: false


image: teaglebuilt/fullflow:dev
pullPolicy: Always

db:
  image: bitnami/postgresql:latest
  pullPolicy: Always
  persistence:
    enabled: false