{{- if eq .Values.global.environment "local" }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-dags
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: {{ .Values.global.airflow.paths.dags }}
{{- end}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-dags
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  volumeName: {{ .Release.Name }}-dags
