apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-db
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Release.Name }}-db
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: {{ .Release.Name }}-db
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.db.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgresql
            - name: POSTGRES_USER
              value: airflow
            - name: POSTGRES_DB
              value: airflow
            - name: POSTGRES_HOST
              value: postgresql