apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-db
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-db
  ports:
    - port: 5432
      targetPort: 5432
