apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-database
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-database
  ports:
  - name: postgresport
    protocol: TCP
    port: 5432
    targetPort: postgresport
  type: ClusterIP