version: '3.5'
services:
  postgres:
    image: bitnami/postgresql:latest
    hostname: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=airflow
    ports:
      - 5432:5432
      
  webserver:
    image: teaglebuilt/fullflow:local
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./src:/usr/local/airflow/src
      - ./logs:/usr/local/airflow/logs
    ports:
      - 8099:8080
    env_file: .env
    environment:
      - ENVIRONMENT=docker
    labels:
      app: "fullflow"
      component: "fullflow-webserver"
    command: webserver

  scheduler:
    image: teaglebuilt/fullflow:local
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./src:/usr/local/airflow/src
      - ./logs:/usr/local/airflow/logs
    env_file: .env
    environment:
      - ENVIRONMENT=docker
    labels:
      app: "fullflow"
      component: "fullflow-scheduler"
    command: scheduler