version: '3.5'
services:
  notebook:
    build: .
    ports:
     - "8089:8089"
    environment:
      JUPYTER_GATEWAY_URL: http://127.0.0.1:9999
    command: notebook

  webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./src:/usr/local/airflow/src
      - ./logs:/usr/local/airflow/logs
    ports:
      - 8099:8080
    env_file: .env
    environment:
      - ENVIRONMENT=docker
    networks:
      - fullflow
    command: webserver

  scheduler:
    build: .
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./src:/usr/local/airflow/src
      - ./logs:/usr/local/airflow/logs
    env_file: .env
    environment:
      - ENVIRONMENT=docker
    command: scheduler

  postgres:
    image: bitnami/postgresql:latest
    hostname: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=airflow
    ports:
      - 5432:5432