{{- if .Values.gateway.kip.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kernel-image-puller
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      name: kernel-image-puller
  template:
    metadata:
      labels:
        name: kernel-image-puller
        app: enterprise-gateway
        component: {{ .Release.Name }}-kernel-puller
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: kernel-image-puller
        image: {{ .Values.gateway.kip.image }}
        imagePullPolicy: {{ .Values.gateway.kip.imagePullPolicy }}
        env:
        - name: KIP_GATEWAY_HOST
          value: "http://enterprise-gateway.enterprise-gateway:{{ .Values.gateway.port }}"
        - name: KIP_INTERVAL
          value: !!str {{ .Values.gateway.kip.interval }}
        - name: KIP_PULL_POLICY
          value: {{ .Values.gateway.kip.pullPolicy }}
        volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
{{- end }}
