apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise-gateway
    component: {{ .Release.Name }}-gateway
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: enterprise-gateway
  namespace: {{ .Values.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.gateway.port }}
    targetPort: {{ .Values.gateway.port }}
  selector:
    gateway-selector: enterprise-gateway
  sessionAffinity: ClientIP
  type: NodePort
{{- if .Values.gateway.k8sMasterPublicIP }}
  externalIPs:
  - {{ .Values.gateway.k8sMasterPublicIP }}
{{- end }}
