{{ if .Values.jobs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: airflow-bin-scripts
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-secret
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
data:
  create_connections.py: |-
{{ .Files.Get "bin/connections.py" | indent 4 }}
  create_variables: |-
{{ .Files.Get "bin/variables.py" | indent 4 }}
  create_users: |-
{{ .Files.Get "bin/users.py" | indent 4 }}
{{ end }}