apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.service.name }}
  labels:
    app: prometheus
    component: {{ .Release.Name }}-server
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    kubernetes.io/name: "Prometheus"
spec:
  ports:
    - name: prometheus
      port: {{ .Values.prometheus.service.port }}
      targetPort: 9090
      protocol: TCP
  selector:
    app: {{ .Values.prometheus.service.name }}
