{{- if .Values.statsd.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-statsd
  labels:
    app: prometheus
    component: {{ .Release.Name }}-statsd
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.statsd.ports.scrape | quote }}
{{- if .Values.statsd.service.extraAnnotations }}
{{- toYaml .Values.statsd.service.extraAnnotations | nindent 4 }}
{{- end }}
spec:
  type: ClusterIP
  selector:
    app: prometheus
    component: {{ .Release.Name }}-statsd
    release: {{ .Release.Name }}
  ports:
    - name: statsd-ingest
      protocol: UDP
      port: {{ .Values.statsd.ports.ingest }}
      targetPort: {{ .Values.statsd.ports.ingest }}
    - name: statsd-scrape
      protocol: TCP
      port: {{ .Values.statsd.ports.scrape }}
      targetPort: {{ .Values.statsd.ports.scrape }}
{{- end }}