apiVersion: v1
kind: Pod
metadata:
  name: ${kernel_username}-${kernel_id}
  namespace: ${kernel_namespace}
  labels:
    kernel_id: ${kernel_id}
    app: enterprise-gateway
    component: kernel
spec:
  restartPolicy: Never
  serviceAccountName: ${kernel_service_account_name}
  containers:
    - name: ${kernel_username}-${kernel_id}
      image: ${kernel_image}
      env:
        - name: EG_RESPONSE_ADDRESS
          value: ${eg_response_address}
        - name: KERNEL_LANGUAGE
          value: ${kernel_language}
        - name: KERNEL_SPARK_CONTEXT_INIT_MODE
          value: ${kernel_spark_context_init_mode}
        - name: KERNEL_NAME
          value: ${kernel_name}
        - name: KERNEL_USERNAME
          value: ${kernel_username}
        - name: KERNEL_ID
          value: ${kernel_id}
        - name: KERNEL_NAMESPACE
          value: ${kernel_namespace}
      securityContext:
        runAsUser: ${kernel_uid}
        runAsGroup: ${kernel_gid}