apiVersion: v1
kind: Service
metadata:
  name: lab
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-lab
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-lab
  ports:
  - port: 9999
    targetPort: 8888
