apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notebook
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-notebook
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  {{- if eq .Values.global.environment "local" }}
  type: NodePort
  {{ end }}
  selector:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-notebook
  ports:
  - port: 8089
    targetPort: 8089
