apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:

      - job_name: 'airflow'
        static_configs: 
          - targets: ['airflow-statsd:9102']
            label: {'component': 'statsd'}
            