apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-webserver-policy
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-webserver
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Release.Name }}-webserver
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          component: controller
          release: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: {{ .Values.webserver.port }}