apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          image: docker.repo1.uhc.com/bitnami/postgresql:latest
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgresql
            - name: POSTGRES_USER
              value: airflow
            - name: POSTGRES_DB
              value: airflow
            - name: POSTGRES_HOST
              value: postgresql
