apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgbouncer
  labels:
    tier: airflow
    component: pgbouncer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.deployment.postgres.ports.pgbouncerScrape | quote }}
spec:
  type: ClusterIP
  selector:
    tier: airflow
    component: pgbouncer
    release: {{ .Release.Name }}
  ports:
    - name: pgbouncer
      protocol: TCP
      port: {{ .Values.deployment.postgres.ports.pgbouncer }}
      targetPort: {{ .Values.deployment.postgres.ports.pgbouncer }}
    - name: pgbouncer-metrics
      protocol: TCP
      port: {{ .Values.deployment.postgres.ports.pgbouncerScrape }}
      targetPort: {{ .Values.deployment.postgres.ports.pgbouncerScrape }}
