apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.service.name }}
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-prometheus
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
    - name: prometheus
      port: {{ .Values.prometheus.service.port }}
      targetPort: 9090
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-prometheus
