apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-webserver
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Release.Name }}-webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: {{ .Release.Name }}-webserver
    spec:
      containers:
        - name: webserver
          image: {{ .Values.image }}
          imagePullPolicy: Always
          args: ["webserver"]
          env:
        {{- include "airflow_default_environment" . | indent 10 }}
          resources:
            limits:
              cpu: 250m
              memory: 1000Mi
            requests:
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: "/health"
              port: web
          ports:
            - containerPort: {{ .Values.webserver.containerPort }}
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: logs
              mountPath: /usr/local/airflow/logs
      volumes:
        - name: logs
          emptyDir: {}