apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-webserver
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Release.Name }}-webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: {{ .Release.Name }}-webserver
    spec:
      containers:
        - name: webserver
          image: {{ .Values.airflow.image }}
          args: ["webserver"]
          envFrom:
            - configMapRef:
                name: airflow-envvars-configmap
          resources:
            limits:
              memory: "2Gi"
              # cpu: "100"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: dags-host-volume
              mountPath: /usr/local/airflow/dags
            - name: logs-persistent-storage
              mountPath: /usr/local/airflow/logs
      volumes:
        - name: dags-host-volume
          hostPath:
            path: /usr/local/airflow/dags
            type: Directory
        - name: logs-persistent-storage
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
