apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-webserver
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-webserver
  ports:
  - port: {{ .Values.webserver.port }}
    targetPort: {{ .Values.webserver.containerPort }}