apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-webserver
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  {{ if .Values.webserver.expose }}
  type: NodePort
  {{ end }}
  selector:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-webserver
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.webserver.port }}
      targetPort: {{ .Values.webserver.containerPort }}