apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-scheduler
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Release.Name }}-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: {{ .Release.Name }}-scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: {{ .Values.airflow.image }}
          args: ["scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-envvars-configmap
          ports:
            - containerPort: 8379
          resources:
            requests:
              memory: 4Gi
              cpu: 2000m
            limits:
              memory: 4Gi
              cpu: 2000m
          volumeMounts:
            - name: logs-persistent-storage
              mountPath: /usr/local/airflow/logs
          securityContext:
            runAsUser: 1000
      volumes:
        - name: logs-persistent-storage
          persistentVolumeClaim:
            claimName: airflow-logs-pvc

