apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
    component: scheduler
spec:
  selector:
    matchLabels:
      app: airflow-scheduler
      component: scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow-scheduler
        component: scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: {{ .Values.airflow.image }}
          args: ["scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-envvars-configmap
          resources:
            limits:
              memory: "512Mi"
              # cpu: "100"
          volumeMounts:
            - name: dags-host-volume
              mountPath: /usr/local/airflow/dags
            - name: logs-persistent-storage
              mountPath: /usr/local/airflow/logs
      volumes:
        - name: dags-host-volume
          hostPath:
            path: /usr/local/airflow/dags
            type: Directory
        - name: logs-persistent-storage
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
