apiVersion: v1
kind: Service
metadata:
  name: scheduler
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-scheduler
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-scheduler
  ports:
  - port: 8739
    targetPort: 8739