kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-scheduler
  labels:
    tier: airflow
    component: scheduler
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.scheduler.type }}
  selector:
    tier: airflow
    component: scheduler
    release: {{ .Release.Name }}
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.service.scheduler.ports.logs }}
      targetPort: {{ .Values.service.scheduler.ports.logs }}