{{- if .Values.statsd.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow-statsd
  labels:
    app: exporters
    component: statsd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporters
      component: statsd
  template:
    metadata:
      labels:
        app: exporters
        component: statsd
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      restartPolicy: Always
      containers:
        - name: statsd
          image: {{ .Values.statsd.image.name }}:{{ .Values.statsd.image.tag }}
          imagePullPolicy: {{ .Values.statsd.image.pullPolicy }}
          args:
            - --statsd.listen-tcp=:9125
            - --web.listen-address=:9102
            - --statsd.mapping-config=/etc/statsd-exporter/mappings.yml
          resources:
{{ toYaml .Values.statsd.resources | indent 12 }}
          ports:
            - name: statsd-ingest
              protocol: UDP
              containerPort: {{ .Values.statsd.ports.ingest }}
            - name: statsd-scrape
              containerPort: {{ .Values.statsd.ports.scrape }}
          securityContext:
            runAsUser: 1000
          livenessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.statsd.ports.scrape }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.statsd.ports.scrape }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: metrics
              mountPath: /etc/statsd-exporter
      volumes:
        - name: metrics
          configMap:
            name: statsd-config
{{- end }}