apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-claim
spec:
  {{- if eq .Values.environment "private" }}
  storageClassName: nas-thin
  {{ end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi