name: CI Testing

on: [push]

jobs:
  lint_chart:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Setup Go environment"
        uses: "actions/setup-go@v2"
        with:
          go-version: '^1.16'

      - name: "Go mod init"
        working-directory: "./chart/tests"
        run: |
          go mod tidy

      - name: Run Linting Tests
        working-directory: "./chart/tests"
        run: go test -v .

  python_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run Pylint
        run: |
          pylint src/

  unit_testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run Application Unit Tests
        run: |
          pytest tests

      - name: Run Integration Tests
        run: |
          pytest tests